export const LOAD_FAVORITES  = 'LOAD_FAVORITES';
export const LOAD_FAVORITES_ARTISTS_COMPLETED  = 'LOAD_FAVORITES_ARTISTS_COMPLETED';
export const LOAD_FAVORITES_TRACKS_COMPLETED  = 'LOAD_FAVORITES_TRACKS_COMPLETED';
