export const LOAD_CHARTS  = 'LOAD_CHARTS';
export const LOAD_CHARTS_COMPLETED  = 'LOAD_CHARTS_COMPLETED';

export const LOAD_GENRES  = 'LOAD_GENRES';
export const LOAD_GENRES_COMPLETED  = 'LOAD_GENRES_COMPLETED';
